import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from '@/components/layout/navbar'
import { Footer } from '@/components/layout/footer'
import { BackgroundAudioPlayer } from "@/components/layout/background_audio_player";
import AppProvider from "@/src/providers/app-provider";
import { getLocale, getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from "next-intl";
import { AppLocale } from "@/src/types/i18n";
import { getDictionary } from "@/src/i18n/dictionaries";
import { FloatingWhatsApp } from "@/components/ui/floating_whatsapp";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  const direction = (locale as AppLocale) == 'en' ? 'ltr' : 'rtl'

  const dictionary = await getDictionary(locale as AppLocale)

  return (
    <html lang={locale} dir={direction}>
      <body
        className={`antialiased ${direction == 'rtl' ? 'font-almarai' : 'font-din'}`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AppProvider>
            <Navbar dictionary={dictionary} />
            <main className="bg-neutral-light">
              {children}
            </main>
            <Footer dictionary={dictionary} />
            <BackgroundAudioPlayer
              tracks={[
                {
                  id: '1',
                  src: '/assets/music/sound1.mp3',
                  title: ''
                },
                {
                  id: '2',
                  src: '/assets/music/sound2.mp3',
                  title: ''
                },
                {
                  id: '1',
                  src: '/assets/music/sound3.mp3',
                  title: ''
                },
              ]}
            />

            <FloatingWhatsApp dictionary={dictionary} />
          </AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
