import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from '@/components/layout/navbar'
import { Footer } from '@/components/layout/footer'
import { BackgroundAudioPlayer } from "@/components/layout/background_audio_player";
import AppProvider from "@/src/providers/app-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AppProvider>
        <Navbar />
        <main className="bg-neutral-light">
          {children}
        </main>
        <Footer />
        <BackgroundAudioPlayer
          tracks={[
            {
              id: '1',
              src: '/assets/music/sound1.mp3',
              title: ''
            },
            {
              id: '2',
              src: '/assets/music/sound2.mp3',
              title: ''
            },
            {
              id: '1',
              src: '/assets/music/sound3.mp3',
              title: ''
            },
          ]}
        />
        </AppProvider>
      </body>
    </html>
  );
}
